# Generated by Django 5.2.12 on 2026-03-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('predicador', models.CharField(blank=True, max_length=255, verbose_name='Predicador')),
                ('tema', models.CharField(blank=True, max_length=255, verbose_name='Serie')),
                ('video_url', models.URLField(blank=True, verbose_name='URL del video')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen_destacada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen destacada')),
            ],
            options={
                'verbose_name': 'Enseñanza',
                'verbose_name_plural': 'Enseñanzas',
                'ordering': ['-fecha'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
