# Generated by Django 5.2.12 on 2026-03-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingpage',
            name='tema',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tema'),
        ),
    ]
