# Generated by Django 5.2.12 on 2026-03-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistriesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción corta')),
                ('lider', models.CharField(blank=True, max_length=255, verbose_name='Líder')),
                ('horario', models.CharField(blank=True, max_length=255, verbose_name='Horario de reunión')),
                ('imagen_destacada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen destacada')),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
