# Generated by Django 5.2.12 on 2026-03-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', models.TextField(blank=True, verbose_name='Introducción')),
            ],
            options={
                'verbose_name': 'Donaciones',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('pse', 'PSE'), ('efectivo', 'Efectivo')], max_length=50, verbose_name='Método de pago')),
                ('numero_cuenta', models.CharField(blank=True, max_length=255, verbose_name='Número de cuenta')),
                ('titular', models.CharField(blank=True, max_length=255, verbose_name='Titular')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen o logo')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
            },
        ),
    ]
