# Generated by Django 5.2.12 on 2026-03-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_boton_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='titulo_destacado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título destacado'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo_normal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título normal'),
        ),
    ]
