# Generated by Django 5.2.12 on 2026-03-13 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_titulo_destacado_homepage_titulo_normal'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_tag',
            field=models.CharField(blank=True, default='Comunidad Cristiana · Turbaco', max_length=255, verbose_name='Tag del hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='boton_texto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto del botón'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='boton_url',
            field=models.URLField(blank=True, verbose_name='URL del botón'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='imagen_hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
    ]
