# Generated by Django 5.2.12 on 2026-03-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_tag_alter_homepage_boton_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_tag',
        ),
        migrations.AddField(
            model_name='homepage',
            name='sede_name',
            field=models.CharField(blank=True, default='Comunidad Cristiana · Central', max_length=255, verbose_name='Nombre de sede'),
        ),
    ]
