# Generated by Django 5.2.12 on 2026-03-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='sede_nombre',
            field=models.CharField(blank=True, default='Comunidad Cristiana · Central', max_length=255, verbose_name='Nombre de la sede'),
        ),
    ]
