# Generated by Django 5.2.12 on 2026-03-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcepage_sede_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='etiqueta',
            field=models.CharField(blank=True, default='Recurso destacado', max_length=100, verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='texto_boton_descarga',
            field=models.CharField(default='Descargar documento', max_length=50, verbose_name='Texto botón descarga'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='texto_boton_externo',
            field=models.CharField(default='Ver recurso externo', max_length=50, verbose_name='Texto botón externo'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='titulo_acento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título con acento de color'),
        ),
    ]
