# Generated by Django 5.2.12 on 2026-03-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourcepage_etiqueta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='titulo_contenido',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título del contenido'),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='texto_boton_descarga',
            field=models.CharField(blank=True, default='Descargar documento', max_length=50, verbose_name='Texto botón descarga'),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='texto_boton_externo',
            field=models.CharField(blank=True, default='Ver recurso externo', max_length=50, verbose_name='Texto botón externo'),
        ),
    ]
