# Generated by Django 5.2.12 on 2026-03-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourcepage_titulo_contenido_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='categoria',
            field=models.CharField(blank=True, choices=[('sermon', 'Sermón en video'), ('devocional', 'Devocional'), ('libro', 'Libro y PDF')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='tiempo_lectura',
            field=models.CharField(blank=True, help_text='Ejemplo: 5 min, 30 min, 1 hora', max_length=50, verbose_name='Tiempo de lectura'),
        ),
        migrations.CreateModel(
            name='ResourceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sede_nombre', models.CharField(blank=True, default='Comunidad Cristiana · Central', max_length=255, verbose_name='Nombre de la sede')),
                ('imagen_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen hero')),
            ],
            options={
                'verbose_name': 'Índice de recursos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
